name: Check New Releases

on:
  # push 삭제됨
  schedule:
    - cron: '17 0-14,23 * * *'
  workflow_dispatch:

jobs:
  check-new:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run new release script
        env:
          DISCORD_WEBHOOK_NEWSALES: ${{ secrets.DISCORD_WEBHOOK_NEWSALES }}
        run: |
          python new_releases.py
          
      - name: Commit and push history
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add sent_new_releases.json
          # [핵심] [skip ci] 추가
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update new releases history [skip ci]" && git pull --rebase && git push)