name: Steam Deck Bot

on:
  schedule:
    # 한국 아침 9:15, 저녁 9:15 (UTC 0:15, 12:15)
    - cron: '15 0,12 * * *'
  workflow_dispatch: # 수동 실행 버튼 추가

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 저장 권한

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot script
        env:  # [추가됨] 봇에게 비밀키 전달
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python main.py

      - name: Commit and push if changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add sent_games.json
          git commit -m "Update game history" || exit 0
          git push
